spring:
  datasource:
    password: Singh123
    url: jdbc:mysql://localhost:3306/sales
    username: root
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
         google:
          redirect-uri: http://localhost:8080/list
          clientId: 94237633752-ju1ekng47bgp5ld4b407l0l4snjm9a6f.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile